# Generated by Django 2.1.7 on 2019-02-26 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('county', models.CharField(max_length=200)),
                ('sub_county', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('credit_amount', models.IntegerField()),
                ('serial', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Product')),
            ],
        ),
    ]
