# Generated by Django 2.1.7 on 2019-02-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('id_no', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('alternative_phone_number', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
