# Generated by Django 2.1.7 on 2019-02-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190227_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_type',
            new_name='ptype',
        ),
    ]
