# Generated by Django 2.1.7 on 2019-02-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='gender',
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=10),
            preserve_default=False,
        ),
    ]
