# Generated by Django 2.1.7 on 2019-03-06 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190306_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.County'),
        ),
    ]
