# Generated by Django 2.1.7 on 2019-03-07 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20190306_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField(default=datetime.date.today)),
                ('customer_name', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=200)),
                ('_id', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('alternative_phone_number', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('sub_county', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=500)),
                ('serial_number', models.CharField(max_length=300)),
                ('total_price', models.IntegerField(null=True)),
                ('deposit', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('repayment_tenure', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=300)),
            ],
        ),
    ]
